### ISSUE TITLE
Change wording

### ISSUE THREAD

**Issue by l00mi** [StrubT/ProgressorMeteor#52]
By the way, I would suggest to rename this label to:
- "logout other users" in case you are talking about other users
- "logout other sessions" in case you are talking about other sesstions of this user
"clients" is ambiguos.

**Comment by StrubT** [comment]
2nd

**Comment by l00mi** [comment]
Wow, you fast, that was Luav proposition by the way.

**Comment by StrubT** [comment]
I'm pretty busy today. I will continue working on the issues again next week.
