### ISSUE TITLE
Promoting user to Admin does not work

### ISSUE THREAD

**Issue by l00mi** [StrubT/ProgressorMeteor#53]
Neither with exact name nor exact email address I was able to promote a user to Admin.

**Comment by StrubT** [comment]
What user did you try to authorise?

**Comment by l00mi** [comment]
User "Test10", it responds with "No element was selected."

**Comment by StrubT** [comment]
It worked when I tried it. I will look into potential sources of a problem.

- Did you try on the production environment? The user only exists in the test environment.
- Did the suggestion drop down open?
- Did you select the item prior to clicking 'make this user an administrator'?

PS: The user is now an administrator, it will no longer show up in the suggestions list.
I will also work on that. I didn't yet find a way to show it as a 'disabled' item.

**Comment by l00mi** [comment]
- Test environment.
- Drop down? That is it I guess, I never got a drop down?

**Comment by l00mi** [comment]
But sure enough it worked now. Closing for now.
